# Generated by Django 4.1.4 on 2023-01-23 14:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_audit_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='summary',
            field=tinymce.models.HTMLField(default="Improve page loading speed: With a page loading speed of 40%, your website is likely loading slowly for many users. This can lead to a poor user experience and can also negatively impact your search engine rankings. To improve page loading speed, you can consider optimizing images, minifying CSS and JavaScript files, and reducing the number of redirects. Acquire backlinks: Backlinks are a key factor in determining a website's ranking in search engines. Acquiring high-quality backlinks from authoritative websites can help improve your website's visibility and credibility. Some ways to acquire backlinks include guest blogging, creating shareable content, and participating in online communities related to your industry. Optimize page titles and meta descriptions: Page titles and meta descriptions are the text that appears in the search results. They should be concise and accurately reflect the content of the page. Including targeted keywords in these elements can help improve your website's visibility in search results. Use header tags appropriately: Header tags (H1, H2, H3, etc.) help break up the content on your webpage and give structure to the page. Using appropriate header tags can help improve the readability of your website and make it easier for search engines to understand the content of your page. Create a sitemap: A sitemap is a file that lists all the pages on your website and helps search engines understand the structure of your website. Creating and submitting a sitemap can help improve the crawlability of your website and make it easier for search engines to discover new pages.", null=True),
        ),
    ]
